version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      TAPgal0bxK7UvxSm01Zg7gZMXVy02fWGDTEzY/XwpR/5olkk3u3CXSTkyg5R7JnDScLftQFxpUxjRq/qD72KaVdae64D6LNDde3QTOKzEGYZvLPQPKKyWCofH236lyaYbiuGFwQmrs66I/ei0d1mrEzg/n/CGStKM9tmOuzMqFi9p/5NZhvgrleD70AAX8iO28cM6BCdtRZGD/3cEMoK61DmNt+AVGGkz+JH8yaMC3PuFlFlj3CKyuvkZFZsadxuCTrTT+KNO7kkDhxg/3Iwk5u0QBHV339+CJpBTl/ttKQSLrbSIeGWpBFGLAnnIbW+VhZ7bYIAe+fcBcL7BG6a5Kl7AEOOyUsw/WWvPaxqVkvi3jrcw2pxZJTwF634D9k/Jjg+t4Qj+GXoZFM8oFTsEMnQYbDKyrSLkSZ7abTXj6ao/p/mFApLGyqMWbZnrGQoafj3TVgTSKit2v/40IaCpbQ3Z4NLYQtVq2z8StRaM96HcwxKc79EZbgGd9vWGGeH04WnTHrEpOrYdIAsdRoZE+BifKUGDQNt2ZTrQO+2kYc8Q2xbDBIVdb6G1MxU5EkdWoPRc3FU9frqAlt51q5N0cvkQAt47xopTMN52A3xSsZmQDT+rnTYlbonueqJlya7pkGoNx8ME3uz1ITT+JwqRKQ+4fWZXzdjTsUT1qIEGgg=
