sudo: false
language: node_js
node_js:
- '4'
- '6'
- '8'
- '10'
- '11'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1f4c6b3d2a0315d3fcd66e8a2cb5de31889ea87d/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1f4c6b3d2a0315d3fcd66e8a2cb5de31889ea87d/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1f4c6b3d2a0315d3fcd66e8a2cb5de31889ea87d/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1f4c6b3d2a0315d3fcd66e8a2cb5de31889ea87d/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: WzVNvB7n/+GlNIX3wDr+3Khuk7Ef/u5DKqalztt8FFLKmvAVGuwhepsoKKJcegXpRE7J5EWt8W2+YveML8umMr8ZH6uqp+opMS6neShfUhIof+jeIWO/bMtIH8jkoCMnfNJirVt/sy3W+I1Ebyzu18hjgfjWpQbqCUldoNoUP+zr/f2BCWiuel0wSgnaRR4NVEfnIYxM7fEFPnS/6nWTcwShhjgdfsjCu5NEdesUO6WabekmBUMnUfG24GyFl2GR4aQtJj369VUt6rdPkxjWYDAlFJlIsGnbfWa1onWrYGOOMD9WVEQ23r76dhFsRWyST/TOqMJELEQUrVO6jns0FdAZdBFrPDdQSn54uszmZRSH6L1awU73hcK/sK1f+NW+1WeJg/j5n+R60RaJFLxGdDnwGwjseEmE2m0/hr3Ry4QMyLxvHn2+nHLRebruSM3lh+8/+UO9zc7de6wQPmAqSwhT+dIVY/jLxv5trpq+aPcCMMcEO/mngDRCvcxVCw/SSReIusPrJOWv/l/mRoqLOFpM0ShwbznBkEPdpbx8J/7zNF4erY109Xt+j4nxI14ZGnTVA2rT9hxnEtkcfIFbPLjJxANMY4n66VbFSX+reMG+oxfMbEsxWSe3+eZXz6jDh3eIxTg1uvGZ8ZR/rWs03lTG6oheLqn5pFxEumiNaR8=
