version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      mRUCQ+R3vGplgYzeIFyO7kUvfSxecz/bRSG+kUCsCVL2LCSH1MFf9OILIL4qXw29tSBYw/EmHGGQDVH1QoZDROLypeMaNbVA6O59jDPl80srjQsH/KntDoxjm/VK7rAD88p8GPlxs0IHXnG2kzux6D7Ee9ox/4f644b20UWqY1sb0wGbiiUr5+JxBCuhmuWpuHEn3EW3KgU+mr1FMKWxmOXctdqPaSv5lYuJJlk/tatOsTgpdu/ufYK2Kb2wzFjtUYTfKRo+emoHY8Rm+XDCJ5W9NYg2fut04pqgHckWZ+5tlisHfbogsrm8HcNdfoqxU44FXS6wQqp+0UhtScEJLStC+T33+d7CBvMdDKqzj72lu+iGRIlaWeWfw/ZbnAAgr7WT9RkHsKNNj5qsrrupC05HeHsVpEB96/EZaKGm+eTt3nbDOUSVByx18CuPFnelqdukFyWAzV4EaZ3VZT2K3n+aP2qrwOLslpxUQ4yPilOBN76RpIQBH0nkCZnWrMMYlEjmJziygTcSrPQ83CNuQxSGhANzYGbqYuj4P4GjXDYgKEWGKWojqSK+wfgCioOg59649h+Qgst3P1wtEbizT+cKqC5mz0j5ehyp9SVLQVWrvmRk40RX4k7vOnyi6057WJoeOEzXrhq2lLcF1yz4QK6OBkK8lUmTOlF4shHgdAw=
