version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      sksjJutUx0LGAoJ3MBNWPJc3tkYc3GuHpLZDLObQaBHEdhrNQfZ1W4G820QADgqJ25q229QlvA502Netbvkv7Rj5unLbR2vfybctgchiFgc/rBNiEjAEgjoAtcrH4020NzYAVD/0zT5LTX31IM9AkPmhtkgsoAWYa7fpZF6iUF8va0w7i0pnOv8EI/vcJ8AuP8xzRI6urO6Im1W8ioHzfgI3VSYn1DKur/kvnLJ5dGTvVFXY804uhzpIE8MeF9/T0qRCJzJG4lQDeXDncP2tVW0HTN+GEi+WAXHaN9CX1EHUx+09iMU1bCKRgcoOvYMOkAXsWVKkpgthERlgl/O6UU00egwZRMljlPHKQV5FsoJLlVZc8lM3sCr2/gxyqWRVf6hcDvV3ZaIUW+R4ahMUkWlxReuYlVHXSvm0H6C6RSYF7DEo3KciDY2KU8phIYV8TF/1CR/umHcZRiDQv0JB7IwWRTnqQZPuhUhZrizeZgWy+j2s83KEnu9JI1ywDlw7geuDwzYFGb0z9IjX2x/MQ+VyJ3vQKVwXkv3S2BdRtmpQ4OMOQOpskCQkLDqD42WJbzmQUjEHOTHbuFK0RBEWFmsc6/JCQPmdNRtS2r9BoSwpL1raDXCVDaBFJDhPUl1oJlK/g5kHxp5hLYKzrwFllaM8K7qIZzxZQF3WKNs0ufM=
