version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      kszHJCWHlxg8tHpUM9rmQH4gpw6yzZBcAr6r/ui4WIUt1l62X8lhuGBCGrugB1BK2sjJ5cmuDnmzpOxqqeWycgosMMshEMOIrm7V/fz/uHBc+HayoO56JV8xGCCyc+Es8cQChc7mjq87DU4Gx7SBD2GtleDeeoTvSR/rfVVsvt/z6c/v48xzP5w5QGrpqVEOYyZt+rUDaDZda8wZyog0tXYKYR6adTZUrJjF8SeIF43FXoAsBNq8VZ0712tUCDL/U7umrUDAcGAmWu7EC0gksHbao4xMOVsNvSxN04qZX1nLtq4b///O3Ii13BGHi0wxd6fyTZ6dPsq5dGOHNaG0AEEHm073EPs7juM4OuNxQO0d438T+EqirGE88khstPc8dOv+Wm843+KzzTdKP4NuxeDx0tsbMspEAS7XMV18MKsjBxxXaordrJeUWLgUNJlcDLhZ7oj1DkCLEcNNob9OQ9clxDVJ/un0MNtJAS3He97Ic9MJmxHgrecyh9Yz4v5EjPx6jXx9mJKuVO6L6oljJqaYdzuWkbLnjyP5L761TBbm6sB6LEZ8/mzvVqsUjWulSjz1HlsCjyM0CCd4pgrb2e+w6HdpUeKDc/tXA8aLonQArFCNj5GA3LJlYEb+MKB5W3JBk+tohtlyqNK+IGcVpPLCf/C4adOvCfeROsZV6Dw=
