sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: s9RPYmBrn8q/6SCeZ3Ld/xUy5HZP7dGhtGsyoxLEriGZK4gst17ZtNVoa4B2CD6tECRz0Z0fJRkXhvhoChPMoK/OiVwfz2nPD33xVUudiQ1uWtmz3hzNJotkUCBIpAX0aqHcsgahYY4INR7hV+F6/gDYL2/VpSCKVUzIUtVyQCO8ZZyhHWBmDSeT4mItvNGlm5i/0lnfBYH9K+N7C+A57QNogbwdO9CmFgOCNBJsu4/+ItCL5+g0z5yKbejWYNWD2WEHvYtHqP9WYnihcg5aOyxHKyEtaVPIGuDCZUZ4PTrJXQg5GGQDdXtmnzEw1pffi/RA4hGmoLESM2a628ExDLmVJ/xOd95Im1qKlz2bgazKw2L+hLyw3I0ZabO/RPR4ERlIb873lob7yVqPmlkIYCxjgxXwzkrj8DzatJGsXhVXA6rYAhUbV0TFyVHpY3nXXXKaz5Ycq0eDWTda3tVP0ZcxN8pvl7Fe2wsYo415FMy1eYR87MBwc73ayg0WTcJsfD3R+rYZyJ+6xx2nV5R+m2/QdIK0mWF0/EKpWdoUw7kueaUTENuYFye+qtBda6PGFSIhKwB1uCmJC9m2TFIwtu6P/UgSdBwG3lPW0JJluGvylYYXuGXXjCFnCFmqAcX024CoOMhL7G6dBbVzcF9RGo7TSjV+wj7B5QwNvaNLd70=
